on:
  push:
    branches:
      - master
jobs:
  deploy_vue_app:
    name: Deploy vue app
    runs-on: ubuntu-latest
    steps:
      - name: setup checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: build dockerfile
        run: docker build -t imadelfetouh99/mosque-admin-ui:latest .
      - name: login into docker-hub
        uses: docker/login-action@v1
        with:
          username: imadelfetouh99
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push to docker-hub
        run: docker push imadelfetouh99/mosque-admin-ui
      - name: transfer docker-compose file
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.PRIVATE_DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.PRIVATE_DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.PRIVATE_DIGITAL_OCEAN }}
          source: "./docker-compose.yaml"
          target: "/root/mosque-admin-ui"
      - name: deploy in digitalOcean
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PRIVATE_DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.PRIVATE_DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.PRIVATE_DIGITAL_OCEAN }}
          script: |
            # stop container
            docker container stop $(docker ps -a | grep imadelfetouh99/mosque-admin-ui:latest | awk '{print $1}')
            # delete all stopped containers
            docker container prune -f
            # delete old image
            docker image rm imadelfetouh99/mosque-admin-ui:latest
            # pull new image
            docker pull imadelfetouh99/mosque-admin-ui:latest
            # navigate to docker-compose file
            cd mosque-admin-ui
            # run new image
            docker-compose up -d
